id: IC1A40043
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:37:55+00:00'
last_modified: '2022-06-08T07:47:56.237236+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN558
  title: སུམ་རྟགས་ཀྱི་འགྲེལ་པ་བློ་གསར་འཇུག་ངོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6E7B:
      image_group_id: I3CN3985
      title: ''
      total_pages: 154
      order: 1
      base_file: 6E7B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
